services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    container_name: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      timeout: 5s
      retries: 10
      start_period: 30s

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    env_file:
      - .env
    volumes:
      - wordpress_html:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    #     condition: service_healthy
    container_name: wordpress
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    env_file:
      - .env
    ports:
      - "8443:443"
    volumes:
      - wordpress_html:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    #     condition: service_healthy
    container_name: nginx
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost"]
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ihadj/data/mariadb
  wordpress_html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ihadj/data/wordpress

networks:
  inception_network:
    driver: bridge